sudo: required

language: generic

notifications:
  email: false

services:
  - docker

before-install:
  - docker build -t diraulo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diraulo/react-test yarn test -- --coverage

after-success:
  - docker build -t diraulo/fancyfib-client ./client
  - docker build -t diraulo/fancyfib-nginx ./nginx
  - docker build -t diraulo/fancyfib-server ./server
  - docker build -t diraulo/fancyfib-worker ./worker

  # Log into Dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Push images to docker hub
  - docker push diraulo/fancyfib-client
  - docker push diraulo/fancyfib-nginx
  - docker push diraulo/fancyfib-server
  - docker push diraulo/fancyfib-worker

deploy:
  provider: elasticbeanstalk

  # Elastic Beanstalk configs
  region: "af-south-1"
  app: "fancyfib"
  env: "Fancyfib-env"
  bucket_name: "elasticbeanstalk-af-south-1-186522626504"
  bucket_path: "fancyfib"

  # Only deploy on push to master
  on:
    branch: master

  # AWS Secrets
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
